### ISSUE TITLE
Started failing with a glibc error

### ISSUE THREAD

**Issue by mwestphal** [mknejp/delete-release-assets#26]
This action recently started failing with:

```
Run mknejp/delete-release-assets@v1
  with:
    token: ***
    repository: f3d-app/f3d
    tag: nightly
    assets: F3D-*-Linux-x86_64-raytracing.*
    fail-if-no-assets: false
    fail-if-no-release: true
  env:
    DISPLAY: :0
    SCCACHE_CACHE: /github/home/.cache/sccache
    DATE_STRING: 20240203
    VTK_COMMIT_SHA: a4cb9c6c90c18a31e225aa4a18df6a591bf8cd3b
/usr/bin/docker exec  ec29d43071e28ef8b65c453255b8290a6e76cc20a40b1c222b2765503c688d81 sh -c "cat /etc/*release | grep ^ID"
/__e/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)
```
