### ISSUE TITLE
Issue with tag

### ISSUE THREAD

**Issue by schembriaiden** [mknejp/delete-release-assets#27]
Hi,

I have a slight issue and need some help. I am trying to remove release pertaining to a tag, and they are not being found.  Could you kindly help me?

```
- name: Delete old GitHub Pre-Releases
    uses: mknejp/delete-release-assets@v1
    with:
      token: ${{ github.token }}
      tag: "v*-rc*" # Delete all pre-releases
      assets: "*"
      fail-if-no-assets: false
```

![image](https://github.com/mknejp/delete-release-assets/assets/81376423/4f1b5645-cb97-4b28-aab0-ac8c3bb1fa8b)

![image](https://github.com/mknejp/delete-release-assets/assets/81376423/2abb149e-64b3-4681-aea6-bf3ecdd09bf0)
